version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-app
    restart: unless-stopped
    expose:
      - "3000"  # Expose port for internal communication with Nginx
    volumes:
      - .:/app  # Mount the current directory to /app in the container, useful for development

  nginx:
    image: docker.arvancloud.ir/nginx:latest
    container_name: nginx-server
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
