version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-app
    restart: unless-stopped
    volumes:
      - ./dist:/usr/share/nginx/html  

  nginx:
    image: docker.arvancloud.ir/nginx:latest
    container_name: nginx-server
    restart: unless-stopped
    ports:
      - "80:80" 
      - "443:443" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  